trigger:
- master

pool:
  vmImage: windows-latest

variables:
- group: npm-tokens

steps:
- checkout: self
  clean: true

- task: NodeTool@0
  displayName: Use node 10
  inputs:
    versionSpec: "10.x"

- script: npm i -g npm@6.14.12 --force
  displayName: Use npm version 6.14.12

- script: npm ci
  displayName: Install npm-dependencies

- script: npm run build
  displayName: Build TFX CLI

- powershell: |
    "//registry.npmjs.org/:_authToken=$env:NPM_TOKEN" | Out-File ".npmrc"
    & npm publish --ignore-scripts _build
    if ($LASTEXITCODE -eq 1) {
      Write-Host "##vso[task.logissue type=warning]Publishing TFX CLI was unsuccessful"
      exit 0
    }
  env:
    NPM_TOKEN: $(npm-automation.token)
  displayName: Publish TFX CLI